stages:
  - build
  - run

variables:
  APP_PORT: "8051"
build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21-alpine
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  tags:
    - bootcamp

run:
  stage: run
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose up -d --build
  only:
    - dev_statistic
  tags:
    - bootcamp