services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: my-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: maven:3.9.9-eclipse-temurin-21-alpine
    container_name: spring-store

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my-database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - .:/app
    working_dir: /app
    command: mvn spring-boot:run

volumes:
  mysql_data:
    driver: local